replicaCount: 1
image:
  repository: nginxdemos/hello
  tag: ""
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  hosts:
    - host: hello.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
